package com.miriamlaurel.wontfix.versions.fix50

import com.miriamlaurel.wontfix.types
import com.miriamlaurel.wontfix.structure._

case class StipulationType(s: String) extends FixField(233, types.FixString(s))

object StipulationType {
  val ABSOLUTE_PREPAYMENT_SPEED = StipulationType("ABS")
  val AMT = StipulationType("AMT")
  val AUTO_REINVESTMENT_AT_OR_BETTER = StipulationType("AUTOREINV")
  val BANK_QUALIFIED = StipulationType("BANKQUAL")
  val BARGAIN_CONDITIONS = StipulationType("BGNCON")
  val COUPON_RANGE = StipulationType("COUPON")
  val CONSTANT_PREPAYMENT_PENALTY = StipulationType("CPP")
  val CONSTANT_PREPAYMENT_RATE = StipulationType("CPR")
  val CONSTANT_PREPAYMENT_YIELD = StipulationType("CPY")
  val ISO_CURRENCY_CODE = StipulationType("CURRENCY")
  val CUSTOM_START_END_DATE = StipulationType("CUSTOMDATE")
  val GEOGRAPHICS_AND_PERCENT_RANGE = StipulationType("GEOG")
  val VALUATION_DISCOUNT = StipulationType("HAIRCUT")
  val FINAL_CPR_OF_HOME_EQUITY_PREPAYMENT_CURVE = StipulationType("HEP")
  val INSURED = StipulationType("INSURED")
  val YEAR_OR_YEAR_MONTH_OF_ISSUE = StipulationType("ISSUE")
  val ISSUERS_TICKER = StipulationType("ISSUER")
  val ISSUE_SIZE_RANGE = StipulationType("ISSUESIZE")
  val LOOKBACK_DAYS = StipulationType("LOOKBACK")
  val EXPLICIT_LOT_IDENTIFIER = StipulationType("LOT")
  val LOT_VARIANCE = StipulationType("LOTVAR")
  val MATURITY_YEAR_AND_MONTH = StipulationType("MAT")
  val MATURITY_RANGE = StipulationType("MATURITY")
  val MAXIMUM_SUBSTITUTIONS = StipulationType("MAXSUBS")
  val PERCENT_OF_MANUFACTURED_HOUSING_PREPAYMENT_CURVE = StipulationType("MHP")
  val MINIMUM_DENOMINATION = StipulationType("MINDNOM")
  val MINIMUM_INCREMENT = StipulationType("MININCR")
  val MINIMUM_QUANTITY = StipulationType("MINQTY")
  val MONTHLY_PREPAYMENT_RATE = StipulationType("MPR")
  val PAYMENT_FREQUENCY_CALENDAR = StipulationType("PAYFREQ")
  val NUMBER_OF_PIECES = StipulationType("PIECES")
  val POOLS_MAXIMUM = StipulationType("PMAX")
  val PERCENT_OF_PROSPECTUS_PREPAYMENT_CURVE = StipulationType("PPC")
  val POOLS_PER_LOT = StipulationType("PPL")
  val POOLS_PER_MILLION = StipulationType("PPM")
  val POOLS_PER_TRADE = StipulationType("PPT")
  val PRICE_RANGE = StipulationType("PRICE")
  val PRICING_FREQUENCY = StipulationType("PRICEFREQ")
  val PRODUCTION_YEAR = StipulationType("PROD")
  val CALL_PROTECTION = StipulationType("PROTECT")
  val PERCENT_OF_BMA_PREPAYMENT_CURVE = StipulationType("PSA")
  val PURPOSE = StipulationType("PURPOSE")
  val BENCHMARK_PRICE_SOURCE = StipulationType("PXSOURCE")
  val RATING_SOURCE_AND_RANGE = StipulationType("RATING")
  val TYPE_OF_REDEMPTION = StipulationType("REDEMPTION")
  val RESTRICTED = StipulationType("RESTRICTED")
  val MARKET_SECTOR = StipulationType("SECTOR")
  val SECURITYTYPE_INCLUDED_OR_EXCLUDED = StipulationType("SECTYPE")
  val SINGLE_MONTHLY_MORTALITY = StipulationType("SMM")
  val STRUCTURE = StipulationType("STRUCT")
  val SUBSTITUTIONS_FREQUENCY = StipulationType("SUBSFREQ")
  val SUBSTITUTIONS_LEFT = StipulationType("SUBSLEFT")
  val FREEFORM_TEXT = StipulationType("TEXT")
  val TRADE_VARIANCE = StipulationType("TRDVAR")
  val WEIGHTED_AVERAGE_COUPON = StipulationType("WAC")
  val WEIGHTED_AVERAGE_LIFE_COUPON = StipulationType("WAL")
  val WEIGHTED_AVERAGE_LOAN_AGE = StipulationType("WALA")
  val WEIGHTED_AVERAGE_MATURITY = StipulationType("WAM")
  val WHOLE_POOL = StipulationType("WHOLE")
  val YIELD_RANGE = StipulationType("YIELD")
}