package com.miriamlaurel.wontfix.versions.fix50

import com.miriamlaurel.wontfix.types
import com.miriamlaurel.wontfix.structure._

case class TrdType(i: Int) extends FixField(828, types.FixInteger(i))

object TrdType {
  val REGULAR_TRADE = TrdType(0)
  val BLOCK_TRADE = TrdType(1)
  val AFTER_HOURS_TRADE = TrdType(10)
  val EFP = TrdType(2)
  val TRANSFER = TrdType(3)
  val LATE_TRADE = TrdType(4)
  val T_TRADE = TrdType(5)
  val WEIGHTED_AVERAGE_PRICE_TRADE = TrdType(6)
  val BUNCHED_TRADE = TrdType(7)
  val LATE_BUNCHED_TRADE = TrdType(8)
  val PRIOR_REFERENCE_PRICE_TRADE = TrdType(9)
  val EXCHANGE_FOR_RISK = TrdType(11)
  val EXCHANGE_FOR_SWAP = TrdType(12)
  val EXCHANGE_OF_FUTURES_FOR = TrdType(13)
  val EXCHANGE_OF_OPTIONS_FOR_OPTIONS = TrdType(14)
  val TRADING_AT_SETTLEMENT = TrdType(15)
  val ALL_OR_NONE = TrdType(16)
  val FUTURES_LARGE_ORDER_EXECUTION = TrdType(17)
  val EXCHANGE_OF_FUTURES_FOR_FUTURES = TrdType(18)
  val OPTION_INTERIM_TRADE = TrdType(19)
  val OPTION_CABINET_TRADE = TrdType(20)
  val PRIVATELY_NEGOTIATED_TRADES = TrdType(22)
  val SUBSTITUTION_OF_FUTURES_FOR_FORWARDS = TrdType(23)
  val ERROR_TRADE = TrdType(24)
  val SPECIAL_CUM_DIVIDEND = TrdType(25)
  val SPECIAL_EX_DIVIDEND = TrdType(26)
  val SPECIAL_CUM_COUPON = TrdType(27)
  val SPECIAL_EX_COUPON = TrdType(28)
  val CASH_SETTLEMENT = TrdType(29)
  val SPECIAL_PRICE = TrdType(30)
  val GUARANTEED_DELIVERY = TrdType(31)
  val SPECIAL_CUM_RIGHTS = TrdType(32)
  val SPECIAL_EX_RIGHTS = TrdType(33)
  val SPECIAL_CUM_CAPITAL_REPAYMENTS = TrdType(34)
  val SPECIAL_EX_CAPITAL_REPAYMENTS = TrdType(35)
  val SPECIAL_CUM_BONUS = TrdType(36)
  val SPECIAL_EX_BONUS = TrdType(37)
  val BLOCK_TRADE2 = TrdType(38)
  val WORKED_PRINCIPAL_TRADE = TrdType(39)
  val BLOCK_TRADES = TrdType(40)
  val NAME_CHANGE = TrdType(41)
  val PORTFOLIO_TRANSFER = TrdType(42)
  val PROROGATION_BUY = TrdType(43)
  val PROROGATION_SELL = TrdType(44)
  val OPTION_EXERCISE = TrdType(45)
  val DELTA_NEUTRAL_TRANSACTION = TrdType(46)
  val FINANCING_TRANSACTION = TrdType(47)
}